version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  backend:
    build: .
    command: sh -c "python manage.py migrate && gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - postgres
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your_secret_key
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydatabase

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
